# Generated by Django 5.2.5 on 2025-09-07 02:04

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('short_name', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=25)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
            ],
        ),
    ]
