# Generated by Django 5.2.5 on 2025-09-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consortium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consortium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblios.consortium')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblios.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'consortium'), name='unique_consortium_membership')],
            },
        ),
    ]
