# Generated by Django 5.2.5 on 2025-09-07 21:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0003_consortium_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('pk', models.CompositePrimaryKey('page_id', 'extraction_id', 'sequence', blank=True, editable=False, primary_key=True, serialize=False)),
                ('extraction_id', models.CharField(blank=True, max_length=50)),
                ('sequence', models.SmallIntegerField(default=1)),
                ('text', models.CharField(max_length=255)),
                ('text_type', models.CharField(choices=[('P', 'Printed'), ('H', 'Handwriting')], max_length=1)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('geo_x_0', models.DecimalField(decimal_places=20, max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('geo_y_0', models.DecimalField(decimal_places=20, max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('geo_x_1', models.DecimalField(decimal_places=20, max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('geo_y_1', models.DecimalField(decimal_places=20, max_digits=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_consortium_membership',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='id',
        ),
        migrations.AddField(
            model_name='membership',
            name='pk',
            field=models.CompositePrimaryKey('organization_id', 'consortium_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblios.organization'),
        ),
        migrations.AddField(
            model_name='page',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblios.document'),
        ),
        migrations.AddField(
            model_name='series',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblios.collection'),
        ),
        migrations.AddField(
            model_name='document',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblios.series'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblios.page'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='unique_page'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('identifier',), name='unique_doc_per_org'),
        ),
    ]
