# Generated by Django 5.2.5 on 2025-09-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0005_userrole'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_doc_per_org',
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('series', 'identifier'), name='unique_doc_per_org'),
        ),
    ]
