# Generated by Django 5.2.6 on 2025-09-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0005_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('E', 'Editor'), ('A', 'Archivist'), ('G', 'Guest')], max_length=1),
        ),
    ]
