# Generated by Django 5.2.5 on 2025-09-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0006_remove_document_unique_doc_per_org_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_roles',
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'organization', 'role'), name='unique_roles'),
        ),
    ]
