# Generated by Django 5.2.6 on 2025-09-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0006_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.SlugField(max_length=5),
        ),
    ]
