# Generated by Django 5.2.6 on 2025-09-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0007_alter_organization_short_name'),
        ('biblios', '0007_remove_userrole_unique_roles_userrole_unique_roles'),
    ]

    operations = [
    ]
