# Generated by Django 5.2.6 on 2025-09-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0007_alter_organization_short_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
