# Generated by Django 5.2.6 on 2025-09-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0008_merge_20250915_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('T', 'Test'), ('A', 'Amazon Web Services')], max_length=1)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblios.organization')),
            ],
        ),
    ]
