# Generated by Django 5.2.6 on 2025-09-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0008_alter_user_managers_remove_user_username_and_more'),
        ('biblios', '0008_merge_20250915_1816'),
    ]

    operations = [
    ]
