# Generated by Django 5.2.6 on 2025-09-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0009_cloudservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
