# Generated by Django 5.2.6 on 2025-09-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0009_merge_20250920_1005'),
        ('biblios', '0011_alter_page_image'),
    ]

    operations = [
    ]
