# Generated by Django 5.2.6 on 2025-09-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0012_merge_0009_merge_20250920_1005_0011_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='print_control',
            field=models.CharField(choices=[('I', 'Include'), ('M', 'Merge With Prior'), ('O', 'Omit')], default='I', max_length=1),
        ),
    ]
