# Generated by Django 5.2.6 on 2025-09-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0013_textblock_print_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='use_long_s_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='textblock',
            index=models.Index(fields=['geo_x_0', 'geo_y_0'], name='biblios_tex_geo_x_0_1cbc8a_idx'),
        ),
    ]
