# Generated by Django 5.2.6 on 2025-09-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0010_alter_user_first_name_alter_user_last_name'),
        ('biblios', '0014_document_use_long_s_detection_and_more'),
    ]

    operations = [
    ]
