# Generated by Django 5.2.6 on 2025-09-27 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0001_squashed_0015_merge_20250926_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='biblios.document'),
        ),
    ]
