# Generated by Django 5.2.6 on 2025-09-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0016_alter_page_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='suggestions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
