# Generated by Django 5.2.6 on 2025-10-03 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0018_collection_slug_consortium_slug_series_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='biblios.organization'),
        ),
        migrations.AlterField(
            model_name='document',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='biblios.series'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.SlugField(max_length=10),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='biblios.page'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_collection_slug'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('short_name',), name='unique_org_shortname'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('collection', 'slug'), name='unique_series_slug'),
        ),
    ]
