# Generated by Django 5.2.7 on 2025-10-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0020_historicalcloudservice_historicalcollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltextblock',
            name='line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltextblock',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textblock',
            name='line',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textblock',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
