# Generated by Django 5.2.7 on 2025-10-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0021_historicaltextblock_line_historicaltextblock_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='textblock',
            options={'ordering': ['line', 'number']},
        ),
    ]
