# Generated by Django 5.2.7 on 2025-10-15 01:48

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0022_alter_page_options_alter_textblock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinCoreMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(blank=True, default=list)),
                ('description', models.JSONField(blank=True, default=list)),
                ('creator', models.JSONField(blank=True, default=list)),
                ('subject', models.JSONField(blank=True, default=list)),
                ('publisher', models.JSONField(blank=True, default=list)),
                ('contributor', models.JSONField(blank=True, default=list)),
                ('date', models.JSONField(blank=True, default=list)),
                ('type', models.JSONField(blank=True, default=list)),
                ('format', models.JSONField(blank=True, default=list)),
                ('identifier', models.JSONField(blank=True, default=list)),
                ('source', models.JSONField(blank=True, default=list)),
                ('language', models.JSONField(blank=True, default=list)),
                ('relation', models.JSONField(blank=True, default=list)),
                ('coverage', models.JSONField(blank=True, default=list)),
                ('rights', models.JSONField(blank=True, default=list)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='biblios.document')),
            ],
            bases=(models.Model, rules.contrib.models.RulesModelMixin),
        ),
    ]
