# Generated by Django 5.2.7 on 2025-10-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblios", "0023_dublincoremetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganization",
            name="primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="primary",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Consortium",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
