# Generated by Django 5.2.7 on 2025-10-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0024_remove_membership_consortium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('I', 'In Progress'), ('R', 'Ready for Review'), ('A', 'Approved')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='published_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('I', 'In Progress'), ('R', 'Ready for Review'), ('A', 'Approved')], default='N', max_length=1),
        ),
    ]
