# Generated by Django 5.2.7 on 2025-10-20 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0025_document_published_url_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltextblock',
            name='confidence',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.999)]),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='confidence',
            field=models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.999)]),
        ),
    ]
