# Generated by Django 5.2.7 on 2025-10-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0001_squashed_0026_alter_historicaltextblock_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltextblock',
            name='print_control',
            field=models.CharField(choices=[('I', 'Include'), ('M', 'Merged'), ('O', 'Omit')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='print_control',
            field=models.CharField(choices=[('I', 'Include'), ('M', 'Merged'), ('O', 'Omit')], default='I', max_length=1),
        ),
    ]
