# Generated by Django 5.2.7 on 2025-10-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0027_alter_historicaltextblock_print_control_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_doc_per_org',
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='biblios.collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='collection',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biblios.collection'),
        ),
        migrations.AlterField(
            model_name='document',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='biblios.series'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('collection', 'identifier'), name='unique_doc_per_org'),
        ),
    ]
