# Generated by Django 5.2.7 on 2025-10-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0028_remove_document_unique_doc_per_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(default=50)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('word',), name='unique_words')],
            },
        ),
    ]
