# Generated by Django 5.2.7 on 2025-10-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0028_remove_document_unique_doc_per_org_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalseries',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical series', 'verbose_name_plural': 'historical Series'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
    ]
