# Generated by Django 5.2.7 on 2025-11-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0029_alter_historicalseries_options_alter_series_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganization',
            name='contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicaltextblock',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='textblock',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
