# Generated by Django 5.2.7 on 2025-11-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0030_historicalorganization_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='identifier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='identifier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
