# Generated by Django 5.2.7 on 2025-11-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0031_historicalpage_identifier_page_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltextblock',
            name='extraction_id',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='extraction_id',
        ),
    ]
