# Generated by Django 5.2.7 on 2025-11-15 23:37

import biblios.models.documents
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblios', '0031_historicalpage_identifier_page_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to=biblios.models.documents.image_path),
        ),
    ]
