name: Bug Report
description: File a bug report for the LibriScan project.
title: "[Bug]: "
labels: ["bug"]
projects: ["CrimsonVision/LibriScan"]
assignees:
  - crimson-vision-lead
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report for LibriScan! Please provide as much detail as possible to help us resolve the issue quickly.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more information (optional)?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Describe the bug in detail. What did you expect to happen, and what actually occurred? Include steps to reproduce (e.g., uploading a document, running OCR).
      placeholder: A bug happened in the document upload process!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: LibriScan Version
      description: What version or commit of LibriScan are you using?
      options:
        - stage branch (Default)
        - main branch
        - Specific commit (please specify in description)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Affected Browsers
      description: Which browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: details
    attributes:
      label: Environment Details, Logs, Context, etc.
      description: Provide any additional details you have.
      placeholder: |
        - Operating System: [e.g., macOS Ventura]
        - Python Version: [e.g., 3.8]
        - Database: [e.g., SQLite]
        - Deployment: [e.g., Local, AWS EC2, Docker]
        - Logs: Paste any relevant logs or error messages (e.g., Django errors, AWS Textract output).
        - Additional details: Any other details, such as specific workflows (e.g., OCR/HTR, metadata extraction) or recent system changes?
    validations:
      required: true
