name: Bug Report
description: File a bug report for the LibriScan project.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["CrimsonVision/LibriScan"]
assignees:
  - crimson-vision-lead
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report for LibriScan! Please provide as much detail as possible to help us resolve the issue quickly.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you if we need more information (optional)?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Describe the bug in detail. What did you expect to happen, and what actually occurred? Include steps to reproduce (e.g., uploading a document, running OCR).
      placeholder: A bug happened in the document upload process!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: LibriScan Version
      description: What version or commit of LibriScan are you using?
      options:
        - stage branch (Default)
        - main branch
        - Specific commit (please specify in description)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Affected Browsers
      description: Which browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide details about your setup (e.g., OS, Python version, database, deployment type).
      placeholder: |
        - Operating System: [e.g., macOS Ventura]
        - Python Version: [e.g., 3.8]
        - Database: [e.g., SQLite]
        - Deployment: [e.g., Local, AWS EC2, Docker]
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Paste any relevant logs or error messages (e.g., Django errors, AWS Textract output). These will be formatted as code automatically.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/CrimsonVision/LibriScan/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other details, such as specific workflows (e.g., OCR/HTR, metadata extraction) or recent system changes?
      placeholder: e.g., This issue occurs when processing handwritten deeds with AWS Textract.
