name: Django Tests

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main", "stage" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.14]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r libriscan/requirements.txt
    - name: Run Tests
      env: # Or as an environment variable
        LB_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        LB_DEBUG: "True"
        LB_ALLOWED_HOSTS: "*"
      run: |
        python libriscan/manage.py test
